// ============================================================================
// Root Project Configuration
// ============================================================================
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

rootProject.name = 'cics-java-liberty-springboot-security'

// ============================================================================
// Subprojects
// ============================================================================
include(':cics-java-liberty-springboot-security-app')
include(':cics-java-liberty-springboot-security-cicsbundle')


